### PR TITLE
fix: fixed value completions in tss and views with word fragment

### LINKED ISSUE #150: Autocompletion in tss replaces text incorrectly
### Describe the Bug
The autocompletion in tss files (maybe in controllers as well) fails when using the completion suggestion while already having a word fragment

### Steps to reproduce the Bug

bug

### Expected Behavior
The suggestion should be applied properly

### Your Environment
| Software | Version |
| ---------------- | ---------- |
| Titanium SDK | 8.3.0 |
| Appcelerator CLI | 7.1.1 |
| VS Code | 1.39.2 |
| vscode-titanium | 0.6.1 |

### PR DESCRIPTION
**Pull request by longton95**
Fixed the completions in tss files where the completions would not take into account the word
fragment already there.

fixes #150

### CODE REVIEW

File: src/providers/completion/styleCompletionItemProvider.ts [hunk 1]
```diff
@@ -194,8 +194,9 @@ export class StyleCompletionItemProvider implements CompletionItemProvider {
 	 *
 	 * @returns {Array}
 	 */
-	public getPropertyValueCompletions (linePrefix, prefix) {
+	public getPropertyValueCompletions (linePrefix, prefix, position, document) {
 		const { properties } = this.completions.titanium;
+		const range = document.getWordRangeAtPosition(position, /([\w\"\.\'\$]+)/);
```
Comment (ewanharris) [inline src/providers/completion/styleCompletionItemProvider.ts]: I think you can skip the escaping when using a special character in character sets?

File: src/providers/completion/styleCompletionItemProvider.ts [hunk 2]
```diff
@@ -194,8 +194,9 @@ export class StyleCompletionItemProvider implements CompletionItemProvider {
 	 *
 	 * @returns {Array}
 	 */
-	public getPropertyValueCompletions (linePrefix, prefix) {
+	public getPropertyValueCompletions (linePrefix, prefix, position, document) {
```
Comment (ewanharris) [inline src/providers/completion/styleCompletionItemProvider.ts]: Update the jsdoc if we're adding new arguments
