### PR TITLE
fix(action-provider): re-enable view code action provider

### LINKED ISSUE #162: View Code Action provider errors with "command 'titanium.insertCodeAction' not found"
### Describe the Bug
In refactoring the project to use TypeScripts strict compile mode, it appears that the [viewCodeActionProvider](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/d9c47ba782fd3bb6dfcf63fc00aa8852ccdc19c9/src/providers/definition/viewCodeActionProvider.ts) has been fixed to actually work.. mostly. It currently errors out with `command 'titanium.insertCodeAction' not found`, I don't want to make that PR even bigger so I'd like to see us fix this separately and evaluate this feature.

### Steps to reproduce the Bug
Steps to reproduce the behavior, e.g.:
1. Open a view file in an alloy project
2. Add `<TextArea id="atextareaid"></TextArea>` into the view
3. Place your cursor inside the value for the `id` property
4. A lightbulb should appear, select one of the options

### Expected Behavior
A style should be generated

### PR DESCRIPTION
**Pull request by longton95**
fixes #162

### CODE REVIEW

File: src/providers/definition/common.ts [hunk 1]
```diff
@@ -48,7 +48,7 @@ export const viewSuggestions: DefinitionSuggestion[] = [
 	{ // id
 		regExp: /id=["'][\s0-9a-zA-Z-_^]*$/,
 		files (): string[] {
-			return getRelatedFiles('tss');
+			return getRelatedFiles('tss', false);
```
Comment (ewanharris) [inline src/providers/definition/common.ts:51]: I think this will remove app.ts for the definition providers too. We probably want to keep that.

Maybe the filtering should be done where `files` is called?

File: src/providers/definition/viewCodeActionProvider.ts [hunk 2]
```diff
@@ -5,45 +5,45 @@ import * as definitionProviderHelper from './definitionProviderHelper';
...
+					if (insertText) {
+						suggestionFiles.forEach((file: string) => {
+							codeActions.push({
+								title: suggestion.title!(path.parse(file).name),
+								command: definitionProviderHelper.insertCommandId,
+								arguments: [ insertText, file ]
+							});
+						});
+					}
+				} else if ((!definitions || definitions.length === 0) && suggestion.i18nString) {
```
Comment (ewanharris) [inline src/providers/definition/viewCodeActionProvider.ts:38]: It looks like the `i18nString` here is never used? It looks to match up with the `i18nSuggestions` in `definitionProviderHelper.ts` which isn't used either

File: src/providers/definition/viewCodeActionProvider.ts [hunk 3]
```diff
@@ -5,45 +5,45 @@ import * as definitionProviderHelper from './definitionProviderHelper';
...
-		// 				arguments: [ word ]
-		// 			});
-		// 		}
-		// 	}
-		// }
+		for (const suggestion of suggestions) {
+			if (suggestion.regExp.test(linePrefix)) {
+				const suggestionFiles = suggestion.files(document, word);
+				const definitionRegexp = suggestion.definitionRegExp!(word);
+				const definitions: any = await definitionProviderHelper.getReferences(suggestionFiles, definitionRegexp, (file, range) => {
```
Comment (ewanharris) [inline src/providers/definition/viewCodeActionProvider.ts:24]: Both the checks below look to assume no definitions returned, is this call redundant?

File: src/extension.ts [hunk 4]
```diff
@@ -97,7 +99,7 @@ function activate (context: vscode.ExtensionContext): Promise<void> {
 
 		// register code action providers
 		// Disable for now - https://github.com/appcelerator/vscode-appcelerator-titanium/issues/162
-		// vscode.languages.registerCodeActionsProvider({ scheme: 'file', pattern: viewFilePattern }, new ViewCodeActionProvider()),
+		vscode.languages.registerCodeActionsProvider({ scheme: 'file', pattern: viewFilePattern }, new ViewCodeActionProvider()),
```
Comment (ewanharris) [inline src/extension.ts:102]: Should we move this into the `definitionProviderHelper.activate` call? If we don't, please remove the comment on line 101.

File: src/providers/definition/viewCodeActionProvider.ts [hunk 5]
```diff
@@ -5,45 +5,45 @@ import * as definitionProviderHelper from './definitionProviderHelper';
...
 
 export class ViewCodeActionProvider implements vscode.CodeActionProvider {
-	public async provideCodeActions (document: vscode.TextDocument, range: vscode.Range): Promise<vscode.CodeAction[]> {
+	public async provideCodeActions(document: vscode.TextDocument, range: vscode.Range): Promise<vscode.Command[]> {
 		const linePrefix = document.getText(new vscode.Range(range.end.line, 0, range.end.line, range.end.character));
 		const wordRange = document.getWordRangeAtPosition(range.end);
 		const word = wordRange ? document.getText(wordRange) : null;
-		const codeActions: vscode.CodeAction[] = [];
+		const codeActions: vscode.Command[] = [];
 		// const word = range ? document.getText(range) : null;
```
Comment (ewanharris) [inline src/providers/definition/viewCodeActionProvider.ts:13]: Remove if not necessary?

File: src/providers/definition/viewCodeActionProvider.ts [hunk 6]
```diff
@@ -5,45 +5,45 @@ import * as definitionProviderHelper from './definitionProviderHelper';
 import { viewSuggestions as suggestions } from './common';
 
 export class ViewCodeActionProvider implements vscode.CodeActionProvider {
-	public async provideCodeActions (document: vscode.TextDocument, range: vscode.Range): Promise<vscode.CodeAction[]> {
+	public async provideCodeActions(document: vscode.TextDocument, range: vscode.Range): Promise<vscode.Command[]> {
```
Comment (ewanharris) [inline src/providers/definition/viewCodeActionProvider.ts:8]: Should this function delegate to the `provideCodeActions` function in `definitionProviderHelper.ts` or should that be removed?
