### PR TITLE
fix(creation): show output when error on app/module creation

### LINKED ISSUE #107: No log output when creating an app/module
### Describe the Bug
When creating an app or module the extension is silent, so if any failures occur there's no clue as to what went wrong. We should pipe this output into a debug console, if we're concerned about displaying unneeded info to the user then we can hold off displaying the output until an error occurs

### PR DESCRIPTION
**Pull request by longton95**
fixes #107

### CODE REVIEW

File: src/terminal.ts [hunk 1]
```diff
@@ -63,10 +63,25 @@ export default class Terminal {
...
+				});
+				proc.stderr.on('data', data => {
+					const message = data.toString();
+					this.channel.append(message);
+				});
+
 				proc.on('close', code => {
 					if (code) {
+						this.channel.show();
 						return reject();
```
Comment (ewanharris) [inline src/terminal.ts]: Maybe if we exit with a 0 exit code clear the channel?
