### PR TITLE
fix(debugger): add support for platform specific breakpoints

### LINKED ISSUE #129: Breakpoints on iOS specific controllers aren't hit
### Describe the Bug
When compiling the drawer sample app the breakpoints in controller `ios/drawer` aren't firing. 

### Steps to reproduce the Bug
- Get the drawer sample app (currently on private). Add a breakpoint in any of the methods that are called (like the open method).
- Click the menu button and the drawer controller will be created/called
- Breakpoint won't hit. It will remain an unverified breakpoint

### Expected Behavior
Breakpoint should hit as it does in other controllers in the same project.

### PR DESCRIPTION
**Pull request by longton95**
Add support for platform-specific breakpoints and subfolders within platform folder

fixes #129

### CODE REVIEW

File: src/debugger/titaniumSourceMapTransformer.ts [hunk 1]
```diff
@@ -22,25 +22,27 @@ export class TitaniumSourceMapTransformer extends BaseSourceMapTransformer {
...
 		if (this.projectType === 'alloy') {
-			const mapDir = path.join(this.appDirectory, 'build', 'map', 'Resources', this.platform);
+			const platform = this.platform === 'ios' ? 'iphone' : this.platform;
+			const mapDir = path.join(this.appDirectory, 'build', 'map', 'Resources', platform);
 			const libDir = path.join(this.appDirectory, 'app', 'lib');
 			const filename = path.basename(pathToGenerated);
 			const relative = path.relative(path.join(this.appDirectory, 'app'), pathToGenerated);
-			const dir = path.dirname(relative);
 			const isLib = pathToGenerated.includes(libDir);
+			let dir = path.dirname(relative);
```
Comment (ewanharris) [inline src/debugger/titaniumSourceMapTransformer.ts]: It looks like we only use `dir` in the else so maybe move the declaration there?

File: src/debugger/titaniumSourceMapTransformer.ts [hunk 2]
```diff
@@ -22,25 +22,27 @@ export class TitaniumSourceMapTransformer extends BaseSourceMapTransformer {
...
 		this.appDirectory = args.projectDir;
-		this.platform = args.platform === 'ios' ? 'iphone' : args.platform;
+		this.platform = args.platform;
 		this.projectType = await determineProjectType(this.appDirectory);
 	}
 
 	public async scriptParsed (pathToGenerated: string, sourceMapUrl: string): Promise<string[]> {
 		if (this.projectType === 'alloy') {
-			const mapDir = path.join(this.appDirectory, 'build', 'map', 'Resources', this.platform);
+			const platform = this.platform === 'ios' ? 'iphone' : this.platform;
```
Comment (ewanharris) [inline src/debugger/titaniumSourceMapTransformer.ts]: Seeing as this isn't the really the proper platform but used in the sourcemaps, maybe something like `sourceMapPlatform`?

File: src/debugger/titaniumSourceMapTransformer.ts [hunk 3]
```diff
@@ -22,25 +22,27 @@ export class TitaniumSourceMapTransformer extends BaseSourceMapTransformer {
...
 			const isLib = pathToGenerated.includes(libDir);
+			let dir = path.dirname(relative);
 			// if its under lib then its at the top level
 			if (filename === 'alloy.js' || filename === 'app.js') {
 				sourceMapUrl = path.join(mapDir, 'app.js.map');
 			} else if (isLib) {
 				const filepath = path.relative(libDir, pathToGenerated);
 				sourceMapUrl = path.join(mapDir, `${filepath}.map`);
 			} else {
+				dir = dir.split('/').filter(e => e !== this.platform).join('/');
```
Comment (ewanharris) [inline src/debugger/titaniumSourceMapTransformer.ts]: Would we need to use `path.sep` here to ensure this also works on windows?
