### PR TITLE
fix(project): add feedback for tiapp validation

### LINKED ISSUE #95: No feedback if the tiapp.xml is invalid
### Describe the Bug
If we fail to parse the tiapp.xml (or timodule.xml), we just don't load and move on.

https://github.com/appcelerator/vscode-appcelerator-titanium/blob/246e77491ad6202391cf24f1f69ad6594235838b/src/project.ts#L143-L165

I believe we should do the following

* Set `this.isTitaniumApp` to true earlier on, if the file `tiapp.xml` exists 
let's be honest, it's a titanium app.
	* This allows us to continue activation
* Report an error to the user
	* It's an error, so we should provide actionable feedback

We set up the watcher on the file so we can reload it once the file is fixed, however we may need to kick off any actions that require a valid tiapp?

### PR DESCRIPTION
**Pull request by longton95**
Add feedback for tiapp validation that highlights the line where there is an issue

Fixes #95

### CODE REVIEW

File: src/project.ts [hunk 1]
```diff
@@ -130,28 +131,45 @@ export class Project {
...
-					json = result;
+				if (err) {
+					error = new InteractionError(`Errors found in tiapp.xml \n ${err}`);
+					error.interactionChoices.push({
+						title: 'Open tiapp.xml',
+						run: async () => {
+							const file = path.join(workspace.rootPath, 'tiapp.xml');
+							const document = await workspace.openTextDocument(file);
+							const columnExp = /Column: (.*?)(?:\s|$)/g;
+							const column = columnExp.exec(err)[1];
```
Comment (ewanharris) [inline src/project.ts]: I think xml2js does tend to throw errors that match this regex, but it might be best to try and have some error handling around these calls returning null rather than the expected array return value

File: src/project.ts [hunk 2]
```diff
@@ -130,28 +131,45 @@ export class Project {
...
-		// tslint:disable-next-line:no-console
+		let error;
 		const rootPath = workspace.rootPath;
 		if (!rootPath) {
-			// tslint:disable-next-line:no-console
 			return;
 		}
 		const filePath = path.join(rootPath, TIAPP_FILENAME);
 		if (utils.fileExists(filePath)) {
+			this.isTitaniumApp = true;
```
Comment (ewanharris) [inline src/project.ts]: I think we might need to introduce another flag here like `isValid` (or similar) that we set on a valid parse of the tiapp.

If I open a project with an invalid tiapp since we now mark the project as a titaniumApp earlier, we error on startup due to trying to access data from the tiapp in [this call](https://github.com/appcelerator/vscode-appcelerator-titanium/blob/36b7708ce01e0df977216e86f983ba7f628134e7/src/extension.ts#L65)
