### PR TITLE
fix(definition): fixed go to definition for event handlers

### LINKED ISSUE #94: Go to definition does not work for event handlers in views
### Describe the Bug
When (on mac) cmd-clicking (or right click -> Go to Definition) on `doClick` below the extension should open `controllers/index.js` to the doClick function declaration. This currently doesn't work

```xml
<Alloy>
	<Window onClick="doClick">
		<Label text="foo"></Label>
	</Window>
</Alloy>
```

```js
function doClick() {
}
$.index.open();
```

### Steps to reproduce the Bug
Steps to reproduce the behavior, e.g.:
1. Paste the above xml and js into the respective view/controller files
2. Right click on `doClick` and select go to definition

### Expected Behavior
The `controllers/index.js` file should open to the doClick function declaration.

Note:

We probably want to verify the other types of go to definition work here as everything goes through the same flow pretty much

### PR DESCRIPTION
**Pull request by longton95**
Fixes #94

### CODE REVIEW

File: src/providers/definition/definitionProviderHelper.ts [hunk 1]
```diff
@@ -219,9 +219,14 @@ export async function getReferences (files, regExp?: RegExp, callback?: any) {
...
 		if (document.getText().length > 0) {
-			for (let matches = regExp.exec(document.getText()); matches !== null; matches = regExp.exec(document.getText())) {
+			const matches = regExp.exec(document.getText());
+			if (!matches) {
+				continue;
+			}
+			for (const match of matches) {
 				const position = document.positionAt(matches.index);
-				definitions.push(callback(file, new Range(position.line, position.character, position.line, 0)));
+				const location = callback(file, new Range(position.line, position.character, position.line, 0));
```
Comment (ewanharris) [inline src/providers/definition/definitionProviderHelper.ts]: Seeing as we don't do anything with `location` other than push it into the array, could we remove the declaration and just push into the array directly?

File: src/providers/definition/common.ts [hunk 2]
```diff
@@ -71,12 +71,12 @@ export const viewSuggestions = [
...
 	{ // handler
-		regExp: /on(.*?)=["']$/,
+		regExp: /on(.*?)=["'][A-Za-z]*$/,
 		files () {
-			return [ related.getTargetPath('js') ];
+			return [ related.getTargetPath('js')];
 		},
 		definitionRegExp (text) {
-			return new RegExp(`function ${text}\\s*?\\(`);
+			return new RegExp(`function ${text}s*?\\(`);
```
Comment (ewanharris) [inline src/providers/definition/common.ts]: I think we need to keep the `\\s` here as without it a function like the below will fail to pick up (note the space before the first parenthesis)

```js
function clearLogs () {
	logger.clearHistory();
	showLogs();
}
```
